apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arbetsprov-app
  namespace: digg-arbetsprov-prod
spec:
  project: arbetsprov
  source:
    repoURL: git@arbetsprov-app-config.git
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arbetsprov-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
