---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app.kubernetes.io/name: arbetsprov-app
  app.kubernetes.io/instance: arbetsprov-app-test
  app.kubernetes.io/version: "0.0.1"
buildMetadata:
  - managedByLabel
